spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/hello?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 0987
  jpa:
    hibernate:
      ddl-auto: none